In [1]:
import numpy as np
from mini_nn.layers import Linear

In [3]:
linear_layer = Linear(in_features=3, out_features=2)

# Properties and Attributes Check

In [8]:
print(f'linear layer input features: {linear_layer.in_features}')
print(f'linear layer output features: {linear_layer.out_features}')

linear layer input features: 3
linear layer output features: 2


In [21]:
print(f'linear layer wegihts shape: {linear_layer.weight.shape}')
print(f'linear layer total weights count: {linear_layer.weight.size}')
print(f'linear layer random weights (initialization stage): \n{linear_layer.weight}')

linear layer wegihts shape: (3, 2)
linear layer total weights count: 6
linear layer random weights (initialization stage): 
[[-0.00447361  0.00462809]
 [-0.00967727  0.00565029]
 [ 0.00502348 -0.01100732]]


In [24]:
print(f'linear layer bias shape: {linear_layer.bias.shape}')
print(f'linear layer total bias count: {linear_layer.bias.size}')
print(f'linear layer bias (initialization stage): \n{linear_layer.bias}')

linear layer bias shape: (1, 2)
linear layer total bias count: 2
linear layer bias (initialization stage): 
[[0. 0.]]


# Forward Pass Check

In [26]:
X = np.array([[1,3,5],
              [2,4,6]]).astype(float)

In [31]:
Y = linear_layer.forward(X)

print(f'X (input) shape: {X.shape}')
print(f'Y (output) shape: {Y.shape}')
print('Y:')
print(Y)

X (input) shape: (2, 3)
Y (output) shape: (2, 2)
Y:
[[-0.00838804 -0.03345766]
 [-0.01751544 -0.0341866 ]]


In [44]:
manual_y = X @ linear_layer.weight + linear_layer.bias
print(f'Manual Y0:\n{manual_y0}')
print(f'Similatiry numerical check passed: {np.allclose(manual_y, Y)}'
)

Manual Y0:
[[-0.00838804 -0.03345766]
 [-0.01751544 -0.0341866 ]]
Similatiry numerical check passed: True


#

# Backpropagation Check

In [54]:
grad_outputs = np.ones_like(Y)

grad_inputs = linear_layer.backward(grad_outputs)

print(f'grad_outputs shape: {grad_outputs.shape}')
print(f'dw shape: {linear_layer.dw.shape}')
print(f'db shape: {linear_layer.db.shape}')
print(f'grad inputs shape: {grad_inputs.shape}')

grad_outputs shape: (2, 2)
dw shape: (3, 2)
db shape: (1, 2)
grad inputs shape: (2, 3)


In [56]:
manual_dw = X.T @ grad_outputs
manual_db = np.sum(grad_outputs, axis=0, keepdims=True)
manual_grad_inputs = grad_outputs @ linear_layer.weight.T

print("dw equal:", np.allclose(linear_layer.dw, manual_dw))
print("db equal:", np.allclose(linear_layer.db, manual_db))
print("grad_inputs equal:", np.allclose(grad_inputs, manual_grad_inputs))

dw equal: True
db equal: True
grad_inputs equal: True
