In [1]:
import numpy as np
from mini_nn.layers import ReLu, Sigmoid, Tanh, Softmax

In [2]:
input = np.array([-1, 1, -2, 0, 3]).astype(float)

In [3]:
relu=ReLu()
tanh = Tanh()
sigmoid = Sigmoid()
softmax = Softmax()

print(f'relu type: {type(relu)}')
print(f'tanh type: {type(tanh)}')
print(f'sigmoid type: {type(sigmoid)}')
print(f'softmax type: {type(softmax)}')

relu type: <class 'mini_nn.layers.relu.ReLu'>
tanh type: <class 'mini_nn.layers.tanh.Tanh'>
sigmoid type: <class 'mini_nn.layers.sigmoid.Sigmoid'>
softmax type: <class 'mini_nn.layers.softmax.Softmax'>


## One Dimention Input Check

In [4]:
# --- FORWARD PROPAGATION ---
relu_output = relu(input)
tanh_output = tanh(input)
sigmoid_output = sigmoid(input)
softmax_output = softmax(input)

print(f'{"input shape:":<30} {input.shape}')
print(f'{"relu forward output shape:":<30} {relu_output.shape}')
print(f'{"tanh forward output shape:":<30} {tanh_output.shape}')
print(f'{"sigmoid forward output shape:":<30} {sigmoid_output.shape}')
print(f'{"softmax forward output shape:":<30} {softmax_output.shape}')
print('='*50)
print(f'{"input:":<16} {input}')
print(f'{"relu output:":<16} {relu_output}')
print(f'{"tanh output:":<16} {tanh_output}')
print(f'{"sigmoid output:":<16} {sigmoid_output}')
print(f'{"softmax output:":<16} {softmax_output}')

input shape:                   (5,)
relu forward output shape:     (5,)
tanh forward output shape:     (5,)
sigmoid forward output shape:  (5,)
softmax forward output shape:  (5,)
input:           [-1.  1. -2.  0.  3.]
relu output:     [0. 1. 0. 0. 3.]
tanh output:     [-0.76159416  0.76159416 -0.96402758  0.          0.99505475]
sigmoid output:  [0.26894142 0.73105858 0.11920292 0.5        0.95257413]
softmax output:  [0.01513469 0.11183108 0.00556774 0.04114036 0.82632613]


In [5]:
# ---BACK PROPAGATION ---
grad_outputs = np.array([0.2, -0.4, 0.7, 0.1, -0.3])

relu_grad = relu.backward(grad_outputs)
tanh_grad = tanh.backward(grad_outputs)
sigmoid_grad = sigmoid.backward(grad_outputs)
softmax_grad = softmax.backward(grad_outputs)

print(f'{"grad output shape:":<30} {grad_outputs.shape}')
print(f'{"relu backward output shape:":<30} {relu_grad.shape}')
print(f'{"tanh backward output shape:":<30} {tanh_grad.shape}')
print(f'{"sigmoid backward output shape:":<30} {sigmoid_grad.shape}')
print(f'{"softmax backward output shape:":<30} {softmax_grad.shape}')

print('=' * 50)

print(f'{"grad outputs:":<16} {grad_outputs}')
print(f'{"relu grad:":<16} {relu_grad}')
print(f'{"tanh grad:":<16} {tanh_grad}')
print(f'{"sigmoid grad:":<16} {sigmoid_grad}')
print(f'{"softmax grad:":<16} {softmax_grad}')

grad output shape:             (5,)
relu backward output shape:    (5,)
tanh backward output shape:    (5,)
sigmoid backward output shape: (5,)
softmax backward output shape: (5,)
grad outputs:    [ 0.2 -0.4  0.7  0.1 -0.3]
relu grad:       [ 0.  -0.4  0.   0.  -0.3]
tanh grad:       [ 0.08399487 -0.16798974  0.04945558  0.1        -0.00295981]
sigmoid grad:    [ 0.03932239 -0.07864477  0.07349551  0.025      -0.013553  ]
softmax grad:    [ 0.00728874 -0.01324171  0.00546525  0.01569883 -0.01521111]


# 2D Input check

In [6]:
# --- FORWARD PROPAGATION ---
x2d = np.array([
    [-1.0,  2.0, -3.0],
    [ 4.0, -5.0,  6.0]
])

# --- forward propagation ---
d2_relu_output = relu(x2d)
d2_tanh_output = tanh(x2d)
d2_sigmoid_output = sigmoid(x2d)
d2_softmax_output = softmax(x2d)

print(f'{"input shape:":<30} {x2d.shape}')
print(f'{"relu forward output shape:":<30} {d2_relu_output.shape}')
print(f'{"tanh forward output shape:":<30} {d2_tanh_output.shape}')
print(f'{"sigmoid forward output shape:":<30} {d2_sigmoid_output.shape}')
print(f'{"softmax forward output shape:":<30} {d2_softmax_output.shape}')

print('=' * 50)

print(f'{"input:":<16}\n{x2d}')
print(f'\n{"relu output:":<16}\n{d2_relu_output}')
print(f'\n{"tanh output:":<16}\n{d2_tanh_output}')
print(f'\n{"sigmoid output:":<16}\n{d2_sigmoid_output}')
print(f'\n{"softmax output:":<16}\n{d2_softmax_output}')

input shape:                   (2, 3)
relu forward output shape:     (2, 3)
tanh forward output shape:     (2, 3)
sigmoid forward output shape:  (2, 3)
softmax forward output shape:  (2, 3)
input:          
[[-1.  2. -3.]
 [ 4. -5.  6.]]

relu output:    
[[0. 2. 0.]
 [4. 0. 6.]]

tanh output:    
[[-0.76159416  0.96402758 -0.99505475]
 [ 0.9993293  -0.9999092   0.99998771]]

sigmoid output: 
[[0.26894142 0.88079708 0.04742587]
 [0.98201379 0.00669285 0.99752738]]

softmax output: 
[[4.71234165e-02 9.46499123e-01 6.37746092e-03]
 [1.19201168e-01 1.47105928e-05 8.80784121e-01]]


In [7]:
# --- BACK PROPAGATION ---
grad_outputs_2d = np.array([
    [0.2, -0.4, 0.7],
    [1.0, 0.5, -0.3]
])

# --- backward propagation ---
d2_relu_grad = relu.backward(grad_outputs_2d)
d2_tanh_grad = tanh.backward(grad_outputs_2d)
d2_sigmoid_grad = sigmoid.backward(grad_outputs_2d)
d2_softmax_grad = softmax.backward(grad_outputs_2d)

print(f'{"grad output shape:":<30} {grad_outputs_2d.shape}')
print(f'{"relu backward output shape:":<30} {d2_relu_grad.shape}')
print(f'{"tanh backward output shape:":<30} {d2_tanh_grad.shape}')
print(f'{"sigmoid backward output shape:":<30} {d2_sigmoid_grad.shape}')
print(f'{"softmax backward output shape:":<30} {d2_softmax_grad.shape}')

print('=' * 50)

print(f'{"grad outputs:":<16}\n{grad_outputs_2d}')
print(f'\n{"relu grad:":<16}\n{d2_relu_grad}')
print(f'\n{"tanh grad:":<16}\n{d2_tanh_grad}')
print(f'\n{"sigmoid grad:":<16}\n{d2_sigmoid_grad}')
print(f'\n{"softmax grad:":<16}\n{d2_softmax_grad}')

grad output shape:             (2, 3)
relu backward output shape:    (2, 3)
tanh backward output shape:    (2, 3)
sigmoid backward output shape: (2, 3)
softmax backward output shape: (2, 3)
grad outputs:   
[[ 0.2 -0.4  0.7]
 [ 1.   0.5 -0.3]]

relu grad:      
[[ 0.  -0.4  0. ]
 [ 1.   0.  -0.3]]

tanh grad:      
[[ 8.39948683e-02 -2.82603299e-02  6.90622602e-03]
 [ 1.34095068e-03  9.07916155e-05 -7.37296422e-06]]

sigmoid grad:   
[[ 0.03932239 -0.04199743  0.03162366]
 [ 0.01766271  0.00332403 -0.00073995]]

softmax grad:   
[[ 2.66110996e-02 -3.34012507e-02  6.79015116e-03]
 [ 1.36488522e-01  9.48872534e-06 -1.36498011e-01]]
