In [1]:
import numpy as np
from mini_nn.layers import ReLu

In [28]:
relu = ReLu()
type(relu)

mini_nn.layers.ReLu.ReLu

# Check the Forward Propagation

In [41]:
forward_input = np.array([-1, 1, -2, 0, 3]).astype(float)
output = relu(forward_input)

print(f'input shape: {forward_input.shape}')
print(f'forward output shape: {output.shape}')
print()
print(f'input: {forward_input}')
print(f'output: {output}')

input shape: (5,)
forward output shape: (5,)

input: [-1.  1. -2.  0.  3.]
output: [0. 1. 0. 0. 3.]


In [42]:
# 2D check:

x = np.array([
    [-1, 2, -3],
    [4, -5, 6]
])

output = relu(x)
print(output)
print(output.shape)

[[0 2 0]
 [4 0 6]]
(2, 3)


# Backward Check

In [46]:
backward_inputs = x + np.sin(2)
relu.backward(backward_inputs)

array([[-0.        ,  2.90929743, -0.        ],
       [ 4.90929743, -0.        ,  6.90929743]])