In [1]:
from mini_nn.optim import SGD
from mini_nn.layers import Linear, ReLu
import numpy as np

In [2]:
linear1 = Linear(3,2)
relu = ReLu()
linear2 = Linear(2,1)

optimizer = SGD(
    layers=[linear1, relu, linear2],
    learning_rate=0.001
)

In [3]:
linear1.dw = np.ones_like(linear1.weight)
linear1.db = np.ones_like(linear1.bias)

linear2.dw = np.full(linear2.weight.shape, fill_value=2)
linear2.db = np.ones_like(linear2.bias)

linear1_weights_before = linear1.weight.copy()
linear1_bias_before = linear1.bias.copy()

linear2_weights_before = linear2.weight.copy()
linear2_bias_before = linear2.bias.copy()

In [4]:
optimizer.step()

In [5]:
print(f'linear1 weights before:\n{linear1_weights_before}')
print(f'linear1 weights after:\n{linear1.weight}')
print('='*30)
print(f'linear bias before:\n{linear1_bias_before}')
print(f'linear bias after:\n{linear1.bias}')

linear1 weights before:
[[ 0.00397871  0.00829135]
 [-0.00389846  0.0051735 ]
 [-0.00458734 -0.0062975 ]]
linear1 weights after:
[[ 0.00297871  0.00729135]
 [-0.00489846  0.0041735 ]
 [-0.00558734 -0.0072975 ]]
linear bias before:
[[0. 0.]]
linear bias after:
[[-0.001 -0.001]]


In [6]:
print(f'linear2 weights before:\n{linear2_weights_before}')
print(f'linear2 weights after:\n{linear2.weight}')
print('='*30)
print(f'linear2 bias before:\n{linear2_bias_before}')
print(f'linear2 bias after:\n{linear2.bias}')

linear2 weights before:
[[-0.00194453]
 [-0.00909092]]
linear2 weights after:
[[-0.00394453]
 [-0.01109092]]
linear2 bias before:
[[0.]]
linear2 bias after:
[[-0.001]]
